# Generated by Django 3.2 on 2021-04-17 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delibird_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counsel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=20)),
                ('counsel_date', models.DateField()),
                ('phonenum', models.CharField(max_length=15)),
                ('store_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('detail_address', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WebErr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('err_log', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DelibirdErr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('err_log', models.TextField()),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delibird_db.robot')),
            ],
        ),
    ]
